version: '3'
services:
  # static-site:
  #   image: dockersamples/static-site
  #   build: ./static-site
  #   ports:
  #     - "8000:80"
  #   restart: always

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      # - "http://host.docker.internal:8000"  # Pointing to the backend service on port 8000
      - "http://backend:8000" 
      # - "--skip-browser-warning"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    # depends_on:
    #   - static-site
  # ngrok2:
  #   image: ngrok/ngrok:latest
  #   command:
  #     - "http"
  #     # - "http://host.docker.internal:8000"  # Pointing to the backend service on port 8000
  #     - "http://frontend:3000"
  #   environment:
  #     NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  #   ports:
  #     - "4041:4040"
  #   # depends_on:
  #     # - static-site

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      # - ./backend:/photo_handler

    ports:
      - "8000:8000"
    depends_on:
      - db
      # - ngrok
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - REACT_APP_API_URL=http://backend:8000  # Use internal backend service
      # - NGROK_API=http://ngrok:4040/api/tunnels
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - ./.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "yes"

  frontend:
    build: 
      context: .  # Ensure this is the root of your project (where the docker-compose.yml is)
      dockerfile: frontend/Dockerfile  # Sp
    ports:
      - "3000:3000"
    depends_on:
      - backend
      # - ngrok
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Use internal backend service
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
    volumes:
      # - ./frontend:/src
      - ./frontend/src:/app/src
      - /app/node_modules  # Optional: This ensures node_modules are not overridden by your local system
    env_file:
      - ./.env

    # working_dir: /frontend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # elasticsearch:
  #   image: elastic/elasticsearch:8.16.2
  #   environment:
  #     - discovery.type=single-node
  #     - ELASTIC_PASSWORD=yourpassword
  #     - xpack.security.enabled=true
  #     - ELASTICSEARCH_USERNAME=user           # Elasticsearch username
  #     - ELASTICSEARCH_PASSWORD=pass123           # Elasticsearch password
  #     - ELASTICSEARCH_SSL_ENABLED=true
  #     - ELASTICSEARCH_SSL_CERTIFICATE=/usr/share/elasticsearch/config/certs/elasticsearch.crt
  #     - ELASTICSEARCH_SSL_KEY=/usr/share/elasticsearch/config/certs/elasticsearch.key
  #     - ELASTICSEARCH_SSL_CA_CERTIFICATE=/usr/share/elasticsearch/config/certs/ca.crt
  #   volumes:
  #     - ./certs:/usr/share/elasticsearch/config/certs  # Mount the certs directory into the container
  #     - esdata:/usr/share/elasticsearch/data  # Use a named volume for Elasticsearch data
  #   ports:
  #     - "9200:9200"  # Elasticsearch default port

  # kibana:
  #   image: kibana:8.16.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=user           # Replace with your actual username
  #     - ELASTICSEARCH_PASSWORD=pass123           # Replace with your actual password
  #     - SERVER_NAME=kibana
  #     - SERVER_HOST=0.0.0.0
  #     - ELASTICSEARCH_SSL_ENABLED=true
  #     - ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITIES=/usr/share/kibana/config/certs/ca.crt
  #     # - xpack.encryptedSavedObjects.encryptionKey=your-encryption-key-here
  #   volumes:
  #     - ./certs:/usr/share/kibana/config/certs  # Mount the
  #     - esdata:/usr/share/elasticsearch/data  # Use a named volume for Elasticsearch data
  #   ports:
  #     - "5601:5601"  # Kibana default port
  #   depends_on:
  #     - elasticsearch


volumes:
  pgdata:
  pgadmin_data:
  esdata:
