# Generated by Django 5.1.4 on 2024-12-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='s3_url',
        ),
        migrations.AlterField(
            model_name='photo',
            name='food_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
