# Generated by Django 5.1.4 on 2024-12-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_identifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodCategory',
            new_name='FoodLabel',
        ),
        migrations.RenameField(
            model_name='foodprediction',
            old_name='category',
            new_name='label',
        ),
    ]
